use_frameworks!
inhibit_all_warnings!

def rx_swift
pod 'RxSwift',    '~> 3.0'
pod 'RxCocoa',    '~> 3.0'
pod 'RxOptional'
pod 'RxDataSources', '~> 1.0'
end

def realm
pod 'RxRealm'
pod 'RealmSwift'
end

target 'Soundy Cloud' do
realm
rx_swift
pod 'Moya',    '~> 8.0'
pod 'Moya-ObjectMapper/RxSwift'
pod 'ObjectMapper', '~> 2.2'

end
target 'Soundy CloudTests' do
  pod 'ObjectMapper', '~> 2.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end
end
